### ISSUE TITLE
Where's keyboard shortcut configured?

### ISSUE THREAD

**Issue by ghost** [lmartel/pinboard-viewer#1]
> use a keyboard shortcut (suggested: Cmd-Shift-P or Ctrl-Shift-P)

Where's this configured?

**Comment by rebecca321** [comment]
You can add keyboard shortcuts within Chrome. The process is explained <a href="http://lifehacker.com/add-custom-keyboard-shortcuts-to-chrome-extensions-for-1595322121">in this Lifehacker article</a>.
